spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        jdbc:
          time_zone: Asia/Seoul
---
spring:
  config:
    activate:
      on-profile: "db-local"

  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(vYvDRWdmolKPvaiAKA+drsuSNdSpFcOjJEJBl4om7BZP/7knAdgUlTOjwsfsfuVwRiqE0UuktxCJ7usfnMkcMx6uMmPIQtcWFVQ//uy9zzFgyPfp5mylCKmBc6Zb0gQ8QDpx31yOkodUptobtRLi3grb4cjVomgopjNiz/HVuxrOCtRk9IghjXwIgZFVLTaCkPnZpsKF+K4HL9l88CJdfw3ZN6fZEFgb)
    username: ENC(RLnBJtbjYugHdhyyZcLycQ==)
    password: ENC(nLnsdxYgE0mgCBowhsuF1g==)
    hikari:
      max-lifetime: 60000
      connection-timeout: 30000
      maximum-pool-size: 10

  redis:
    port: 6379
    host: localhost
---
spring:
  config:
    activate:
      on-profile: "db-dev"

  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(nKu8gbep+Dn30VE+uDuNnBoiuBOrisF0ChuyeM/y3/t7KVmHlr0AnWEyTLrt3D4/Z6p96RvCbT1a+NdQTcl1vym26MHFjjXJCv6Gxt5R8P4OHX9nHqtMLqsS1ioB+gXuPpDn2y2ylyWPP779tPXnKo4AcOHyhJdmmFTvXFziALj9LZ8Sgs1wVkK9qw6K4pGPeWDbTt8BpHLbgWk7JcwJWNxBcOLNwc6dVxQhVXtRnT0PdsafMB2eni6WymLjwp6wJMmjiiCVHLO41Cj+I6hmOQ==)
    username: ENC(yJuQnspYSDCbL46e75qlJw==)
    password: ENC(BJkU4JUqt2rujKlM42LoZr50842ns5zlxdeu6sdt/FE=)
    hikari:
      max-lifetime: 60000
      connection-timeout: 30000
      maximum-pool-size: 10

  redis:
    port: 6379
    host: localhost

---
spring:
  config:
    activate:
      on-profile: "db-test"

  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(IG3nk4RAt92bHhyThDj+Vw/C1bdsjcxopU7qgcHc/qumAoeARn1gfwC09aeCpnSeOZo2EsrJsRJRdbvJMM2KVsqOrOwWtSNt3ds5iS3IaVkosbZm5bYRH/0OJ+139gsnY9Vr8su8Pz3uORCJgnOJbghWrVZLJ0I5c4268gKZa1B2fVC5KMw+oaQJ631jiIBgufaWtKV7KPHlOS2LPpmgcQ==)
    username: ENC(PsJ4IZm58TJkm2kpxsy+Kg==)
    password: ENC(HC5aZC9e1uoiyKV5i2mAmw==)
    hikari:
      max-lifetime: 60000
      connection-timeout: 30000
      maximum-pool-size: 10

  redis:
    port: 6379
    host: localhost
