spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        jdbc:
          time_zone: Asia/Seoul
---
spring:
  config:
    activate:
      on-profile: "db-prod"

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(iuKEao2RjrPs1AK1eLyuzaCdXnBo2Q9xXGm7ZK3RzDF/+zfQW26w4JR5pcp3eKVhDsb6j9FDxlzwqf0K2eVmEgNHG4kzJGBnV3wvTOz19nJ5cO9rHGdLoOtDT/hFZ7YeBKa5grG5oyyer6T5rI80J4NxWL4DUjJpgZ8IW6hOzMKXHyMLdWYZ4t2/NvXo+txzSRqYQiL/O+v1GsOSmoHWuIiUZOvD+Wy0eaX69GsY57AXagFc3AHtJ2tRYq4fn+4ukk6zeM8CGleqfchhd5Efax1cbfWuM+RXuHhyyWiuv97WaWUD3BDEz+ltPziG9YCFW0nOQLTf4b2UEpqEelu2sQ==)
    username: ENC(S2Fr7azUD6+2P7cwt8UF1uNS2yFgz/ab)
    password: ENC(mfnUX1gJaOyjdsUT2qyJ/OjCDFgY73SM)
    hikari:
      max-lifetime: 60000
      connection-timeout: 30000
      maximum-pool-size: 10

  redis:
    port: ENC(NmLvXHepNpqXSnmI3c1iyg==)
    host: ENC(yhvtw5a7wJaKTeT4m7q/wOBGszX+5upK2K3jcTkn/N9Ho6g/UXXXtk8E5jf9kS1JCVEF9/2b8QeE/5NZRQ9e4g==)
---
spring:
  config:
    activate:
      on-profile: "db-local"

  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(vYvDRWdmolKPvaiAKA+drsuSNdSpFcOjJEJBl4om7BZP/7knAdgUlTOjwsfsfuVwRiqE0UuktxCJ7usfnMkcMx6uMmPIQtcWFVQ//uy9zzFgyPfp5mylCKmBc6Zb0gQ8QDpx31yOkodUptobtRLi3grb4cjVomgopjNiz/HVuxrOCtRk9IghjXwIgZFVLTaCkPnZpsKF+K4HL9l88CJdfw3ZN6fZEFgb)
    username: ENC(RLnBJtbjYugHdhyyZcLycQ==)
    password: ENC(nLnsdxYgE0mgCBowhsuF1g==)
    hikari:
      max-lifetime: 60000
      connection-timeout: 30000
      maximum-pool-size: 10

  redis:
    port: 6379
    host: localhost
---
spring:
  config:
    activate:
      on-profile: "db-dev"

  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(nKu8gbep+Dn30VE+uDuNnBoiuBOrisF0ChuyeM/y3/t7KVmHlr0AnWEyTLrt3D4/Z6p96RvCbT1a+NdQTcl1vym26MHFjjXJCv6Gxt5R8P4OHX9nHqtMLqsS1ioB+gXuPpDn2y2ylyWPP779tPXnKo4AcOHyhJdmmFTvXFziALj9LZ8Sgs1wVkK9qw6K4pGPeWDbTt8BpHLbgWk7JcwJWNxBcOLNwc6dVxQhVXtRnT0PdsafMB2eni6WymLjwp6wJMmjiiCVHLO41Cj+I6hmOQ==)
    username: ENC(yJuQnspYSDCbL46e75qlJw==)
    password: ENC(BJkU4JUqt2rujKlM42LoZr50842ns5zlxdeu6sdt/FE=)
    hikari:
      max-lifetime: 60000
      connection-timeout: 30000
      maximum-pool-size: 10

  redis:
    port: 6379
    host: localhost

---
spring:
  config:
    activate:
      on-profile: "db-test"

  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8:///?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true
    username: test
    password: test
    hikari:
      max-lifetime: 60000
      connection-timeout: 30000
      maximum-pool-size: 10
