name: main-cd

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  deploy_if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Timezone # 테스트 환경에서의 timezone 설정
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: Asia/Seoul

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew # 실행 권한 부여
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build -x test -Djasypt.password=${{ secrets.JASYPT_PASSWORD }}
        shell: bash

        # grandle build를 통해 만들어진 jar를 beanstalk에 배포하기 위한 zip 파일로 만드는 것
      - name: Generate deployment package
        run: |
          mkdir -p deploy
          cp build/libs/*.jar deploy/application.jar  
          cp Procfile deploy/Procfile
          cp -r .ebextensions deploy/.ebextensions
          cp -r .platform deploy/.platform
          cd deploy && zip -r deploy.zip . 

        # Beanstalk Deploy 플러그인 사용
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: couplog # EB application 이름
          environment_name: Couplog-env # EB environment 이름
          version_label: V1.0 # 배포 버전
          region: ap-northeast-2
          deployment_package: deploy/deploy.zip
          wait_for_environment_recovery: 60
