name: pr-test

on:
  pull_request:
    branches: [ dev, main ]
    types: [opened, reopened]

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SetTimezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: Asia/Seoul

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Gradle Caching # gradle 캐싱
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew # 실행 권한 부여
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build -Djasypt.password=${{ secrets.JASYPT_PASSWORD }}
        shell: bash

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'
